# Generated by Django 5.0.6 on 2024-06-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=10, verbose_name='Option disponible')),
            ],
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Couleur disponible'),
        ),
    ]
