# Generated by Django 5.0.6 on 2024-06-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0002_livraison_alter_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Couleur disponible'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='option',
            field=models.CharField(max_length=25, verbose_name='Option disponible'),
        ),
    ]
