# Generated by Django 5.0.6 on 2024-06-21 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0003_alter_color_name_alter_livraison_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='online_store.color'),
        ),
        migrations.AddField(
            model_name='products',
            name='livraison',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online_store.livraison'),
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
