# Generated by Django 5.0.6 on 2024-06-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0004_products_color_products_livraison_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image1',
            field=models.ImageField(default='', null=True, unique=True, upload_to='./img', verbose_name='image 2'),
        ),
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.ImageField(default='', null=True, unique=True, upload_to='./img', verbose_name='image 3'),
        ),
        migrations.AddField(
            model_name='products',
            name='image3',
            field=models.ImageField(default='', null=True, unique=True, upload_to='./img', verbose_name='image 4'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, unique=True, upload_to='./img', verbose_name='image'),
        ),
    ]
