# Generated by Django 5.0.6 on 2024-06-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0005_products_image1_products_image2_products_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='top_category',
            field=models.BooleanField(default=0, verbose_name='Top categorie'),
        ),
    ]
