# Generated by Django 5.0.6 on 2024-07-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0007_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='top_category',
            field=models.BooleanField(default=0, verbose_name='Tendance'),
        ),
    ]
