# Generated by Django 5.0.6 on 2024-07-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0011_alter_products_image1_alter_products_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image1',
            field=models.ImageField(default='img/deflaut1.jpg', null=True, upload_to='./img', verbose_name='image 2'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.ImageField(default='img/deflaut2.jpg', null=True, upload_to='./img', verbose_name='image 3'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.ImageField(default='img/deflaut3.jpg', null=True, upload_to='./img', verbose_name='image 4'),
        ),
    ]
