# Generated by Django 5.0.6 on 2024-08-10 20:57

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0015_alter_commande_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lieu',
            options={'verbose_name_plural': 'Lieux'},
        ),
        migrations.AlterField(
            model_name='commande',
            name='montant',
            field=models.FloatField(default=1, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='name_and_quantity',
            field=models.CharField(max_length=50, verbose_name='Nom & Quantité'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='', unique=True, upload_to='./img', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image1',
            field=models.ImageField(default='', unique=True, upload_to='./img', verbose_name='image 2'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.ImageField(default='', null=True, unique=True, upload_to='./img', verbose_name='image 3'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.ImageField(default='', null=True, unique=True, upload_to='./img', verbose_name='image 4'),
        ),
    ]
