# Generated by Django 5.0.6 on 2024-08-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0016_alter_lieu_options_alter_commande_montant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.ImageField(default='deflaut1.jpg', null=True, upload_to='./img', verbose_name='image 3'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.ImageField(default='deflaut1.jpg', null=True, upload_to='./img', verbose_name='image 4'),
        ),
    ]
