# Generated by Django 5.0.6 on 2024-08-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0020_alter_products_image2_alter_products_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='./img_category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='', unique=True, upload_to='./img1_pack', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image1',
            field=models.ImageField(default='', unique=True, upload_to='./img2_pack', verbose_name='image 2'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='./img3_pack', verbose_name='image 3'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='./img4_pack', verbose_name='image 4'),
        ),
    ]
