# Generated by Django 5.0.6 on 2024-08-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0021_alter_category_image_alter_products_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image1',
            field=models.ImageField(blank=True, default='', null=True, unique=True, upload_to='./img2_pack', verbose_name='image 2'),
        ),
    ]
