# Generated by Django 5.0.6 on 2024-08-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0022_alter_products_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='./img2_pack', verbose_name='image 2'),
        ),
    ]
