# Generated by Django 5.0.6 on 2024-08-16 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0025_commande2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande2',
            options={'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes_2'},
        ),
        migrations.AlterField(
            model_name='commande2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
    ]
