# Generated by Django 5.0.6 on 2024-08-16 08:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0026_alter_commande2_options_alter_commande2_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commande2',
            new_name='Commande',
        ),
    ]
