# Generated by Django 5.0.6 on 2024-08-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0027_rename_commande2_commande'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(default='En attente.', max_length=25, verbose_name='statue'),
        ),
    ]
