# Generated by Django 5.0.6 on 2024-08-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0028_alter_commande_options_commande_statut'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lieu',
        ),
    ]
