# Generated by Django 5.0.6 on 2024-08-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0029_delete_lieu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nom du lien')),
                ('url', models.URLField(blank=True, verbose_name='lien')),
            ],
        ),
    ]
