# Generated by Django 5.0.6 on 2024-08-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_store", "0030_lien"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.TextField(
                default="...sur Hkar Service", verbose_name="Description"
            ),
        ),
    ]
