# Generated by Django 5.0.6 on 2024-09-23 12:46

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_store", "0031_alter_products_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="NosCollaborateurs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=20, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=20, verbose_name="Prenom")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="ML", verbose_name="Telephone"
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Nom de l'entreprise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collaborateur",
                "verbose_name_plural": "Nos Collaborateurs",
            },
        ),
    ]
