# Generated by Django 5.0.6 on 2024-10-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_store", "0033_alter_commande_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statue",
                    models.CharField(
                        default="En attente..",
                        max_length=15,
                        null=True,
                        verbose_name="statue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statue",
            },
        ),
    ]
