# Generated by Django 5.0.6 on 2024-10-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("online_store", "0034_statue"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Commande",
        ),
    ]
