# Generated by Django 5.0.6 on 2024-10-22 17:02

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_store", "0035_delete_commande"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="Nom"
                    ),
                ),
                (
                    "number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Numéro de téléphone"
                    ),
                ),
                (
                    "adresse",
                    models.CharField(max_length=50, verbose_name="Lieu de résidence"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantité de commande"
                    ),
                ),
                ("montant", models.FloatField(default=1, verbose_name="Montant")),
                (
                    "details",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="detail"
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="online_store.products",
                    ),
                ),
                (
                    "statue",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="online_store.statue",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande",
                "verbose_name_plural": "Commandes",
            },
        ),
    ]
