# Generated by Django 5.0.6 on 2024-11-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_store", "0038_alter_jeton_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="state",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="panier_etat"
            ),
        ),
    ]
