# Generated by Django 5.0.6 on 2024-11-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_store", "0040_remove_commande_state_commande_jeton"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="jeton",
            field=models.BooleanField(
                blank=True,
                default=False,
                editable=False,
                null=True,
                verbose_name="jeton",
            ),
        ),
    ]
